version: "3.9"

services:
    database_fwd:
        image: postgres
        container_name: database_fwd
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=fwdtest
            - POSTGRES_DB=fwdback
        volumes:
            - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local